# Generated by Django 2.2.5 on 2022-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('the_class', models.CharField(max_length=10)),
                ('dormitory', models.CharField(max_length=18)),
            ],
        ),
    ]
