# Generated by Django 2.2.5 on 2022-07-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220712_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
